# Generated by Django 3.0.7 on 2020-10-15 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squrriels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(help_text='longitude of squirrels')),
                ('latitude', models.FloatField(help_text='latitude of squirrels')),
                ('unique_squirrel_id', models.CharField(help_text='unique id of squirrels', max_length=50)),
                ('shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='Unknown', help_text='shift choice, AM or PM', max_length=2)),
                ('date', models.DateField(help_text='date seen')),
                ('age', models.CharField(choices=[('Juvenile', 'Juvenile'), ('Adult', 'Adult')], default='Unknown', help_text='Age of squirrel', max_length=50)),
                ('primary_fur_color', models.CharField(choices=[('Black', 'Black'), ('Gray', 'Gray'), ('Cinnamon', 'Cinnamon')], default='Unknown', help_text='Primary fur color', max_length=50)),
                ('location', models.CharField(choices=[('Above Ground', 'Above ground'), ('Ground Plane', 'Ground plane')], default='Unknown', help_text='location: above ground or ground plane', max_length=50)),
                ('specific_location', models.TextField(blank=True)),
                ('running', models.BooleanField(help_text='whether the squirrel is running')),
                ('chasing', models.BooleanField(help_text='whether the squirrel is chasing')),
                ('climbing', models.BooleanField(help_text='whether the squirrel is climbing')),
                ('eating', models.BooleanField(help_text='whether the squirrel is eating')),
                ('foraging', models.BooleanField(help_text='whether the squirrel is foraging')),
                ('other_activities', models.TextField(blank=True, help_text='other activities', max_length=150)),
                ('kuks', models.BooleanField(help_text='kuks sound')),
                ('quaas', models.BooleanField(help_text='quaas sound')),
                ('moans', models.BooleanField(help_text='moans sound')),
                ('tail_flags', models.BooleanField(help_text='whether the squirrel is flagging tail')),
                ('tail_twitches', models.BooleanField(help_text='whether the squirrel is twitching tail')),
                ('approaches', models.BooleanField(help_text='whether the squirrel is approaching')),
                ('indifferent', models.BooleanField(help_text='whether the squirrel is indifferent')),
                ('runs_from', models.BooleanField(help_text='whether the squirrel is running away')),
            ],
        ),
    ]
