# Generated by Django 3.0.7 on 2020-10-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20201015_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrels',
            name='age',
            field=models.CharField(choices=[('Juvenile', 'Juvenile'), ('Adult', 'Adult')], help_text='Age of squirrel', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='location',
            field=models.CharField(choices=[('Above Ground', 'Above ground'), ('Ground Plane', 'Ground plane')], help_text='location: above ground or ground plane', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='other_activities',
            field=models.CharField(help_text='other activities', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='primary_fur_color',
            field=models.CharField(choices=[('Black', 'Black'), ('Gray', 'Gray'), ('Cinnamon', 'Cinnamon')], help_text='Primary fur color', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='shift',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], help_text='shift choice, AM or PM', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='specific_location',
            field=models.CharField(help_text='Sepecific location', max_length=100, null=True),
        ),
    ]
