# Generated by Django 3.0.7 on 2020-10-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20201017_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrels',
            name='other_activities',
            field=models.CharField(blank=True, help_text='other activities', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='specific_location',
            field=models.CharField(blank=True, help_text='Sepecific location', max_length=100, null=True),
        ),
    ]
